### ISSUE TITLE
Running npx cypress run is not creating the folder /test-results with the failed tests

### ISSUE THREAD

**Issue by CaiqueCoelho** [dennisbergevin/cypress-plugin-last-failed#13]
I'm using Cypress in version "13.15.0" and when I run Cypress with `npx cypress run --env grepTags=@TestFail`
I have some Cypress tests failing but the folder /test-results is not created.

I'm using the tag @TestFail to target some specific tests I know will fail
![Screenshot 2024-10-11 at 18 28 29](https://github.com/user-attachments/assets/31575c45-37b7-4e06-8691-baa42ea10505)

I have also run `npx cypress-plugin-last-failed run --e2e --browser electron` to see if the plugin installation was fine and I just got:
```
No previous failed tests detected
Ensure you are in the directory of your cypress config
Try running tests again with cypress run
```

Could you please help me? I can give you more details if you want

**Comment by dennisbergevin** [comment]
Hi @CaiqueCoelho thanks for reaching out!

An initial question:

Can you check to ensure you've followed the plugin's [Installation instructions](https://github.com/dennisbergevin/cypress-plugin-last-failed?tab=readme-ov-file#-installation) thoroughly, the absence of a `test-results` directory being created _may_ be pointing to missing the `collectFailingTests` within `setupNodeEvents` in the config.

**Comment by CaiqueCoelho** [comment]
Hey @dennisbergevin thank you so much for your quick answer and help.

I read all the installation instructions again and looks like everything is fine
![Screenshot 2024-10-13 at 20 29 44](https://github.com/user-attachments/assets/ea9ff4ea-1df0-45db-9b1b-0f8ea1284336)
![Screenshot 2024-10-13 at 20 29 35](https://github.com/user-attachments/assets/d69a609f-2985-4e66-ac8b-c7b63343f62a)

The funny thing is, running in the open Cypress mode the plugin works perfectly, but I see even this way the folder is not created, but I'm not sure if the folder is only created in the run mode
<img width="442" alt="Screenshot 2024-10-13 at 20 47 24" src="https://github.com/user-attachments/assets/63a004ff-bd58-4099-a08a-5ffbe51bc232">
<img width="484" alt="Screenshot 2024-10-13 at 20 46 52" src="https://github.com/user-attachments/assets/d1ac3932-acc6-4bc3-9ba3-56ba9cd73d35">

Is there any debug mode I can add to see any logs? I'll try some experiments tomorrow, and if I discover anything new, I'll share the details here. Thank you so much

**Comment by dennisbergevin** [comment]
Hey @CaiqueCoelho, thanks for the reply. 

The `open` mode will not create a `test-results` directory, as the toggle pertains to filtering failed tests per each spec file respectively.

Without really understanding your `setupNodeEvents` setup, my overall suggestion for debugging would be to remove or comment out everything in your `setupNodeEvents` other than the following pieces:

```js
...
    setupNodeEvents(on, config) {
      collectFailingTests(on, config);

      require('@bahmutov/cy-grep/src/plugin')(config);
      return config;
    },
...
```

Ensure the plugin works as intended from this setup, then, work backward by adding a little more back into your `setupNodeEvents` and observe the behavior. 

Please feel free to reach out with any more questions or concerns, or if you find a solution feel free to share here.
