### ISSUE TITLE
.skip test cases also showing under failed test

### ISSUE THREAD

**Issue by SubramanyamPalla** [dennisbergevin/cypress-plugin-last-failed#3]
Hi Team,

I've started using the **cypress-plugin-last-failed** and i observed that it is considering **.skip** test cases as failed test cases. And the retry passed test cases are also considered failed test cases.

**Comment by dennisbergevin** [comment]
Hi @SubramanyamPalla, thank you for reaching out!

Just to confirm, you are speaking of the filter toggle behavior within `cypress open`?

**Comment by SubramanyamPalla** [comment]
Hi @dennisbergevin 

Thank you for the updates, yes i'm speaking of the filter toggle behavior within cypress open.

Please find the screen attached here for reference.

1. 1st screenshot 1 failed test case + 4 skip test cases are there
2. When i use the **Filter failed test cases**  the addon is picking up the **1 failed test case + 4 skip test cases**
3. The addon is picking up the test cases which are passed in retry( i.e. In first try the test case is failed but on retry the cases is passed) 


I'm expected the addon should pick up only 1 test case which is failed.

**Image 1**
![image](https://github.com/dennisbergevin/cypress-plugin-last-failed/assets/132259532/59bc8428-a992-4904-8911-f65024749f92)

**Image2:**
![image](https://github.com/dennisbergevin/cypress-plugin-last-failed/assets/132259532/b51a12e7-25f4-4aab-b2e1-6375ba739b00)

**Comment by dennisbergevin** [comment]
@SubramanyamPalla A new [Version 1.0.2](https://github.com/dennisbergevin/cypress-plugin-last-failed/releases/tag/v1.0.2) is now available. 

Please take special note regarding the suggestion on handling skipped tests, using `required tag` from the `@bahmutov/cy-grep` package.

Please feel free to reach out if you have any further issues!
